"""
Synthetic semantic feature analysis for HybridV4.

This script reads the semantic signal reports generated by
`analyze_semantic_error_signals.py`, constructs higher-order synthetic features,
compares groups, and simulates conservative diagnostic rules.

Run from project root:
    python -m Models.HybridV4.analysis.analyze_synthetic_semantic_features

Optional:
    python -m Models.HybridV4.analysis.analyze_synthetic_semantic_features --task gender
    python -m Models.HybridV4.analysis.analyze_synthetic_semantic_features --task occupation

Important:
    This is post-hoc error analysis on existing prediction outputs. Do not report
    rule results as final tuned test performance.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import statistics
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional, Sequence, Tuple

SCRIPT_VERSION = "synthetic-semantic-features-v1"

# Keep import style compatible with the other HybridV4 analysis scripts.
PROJECT_ROOT = os.path.dirname(
    os.path.dirname(
        os.path.dirname(
            os.path.dirname(os.path.abspath(__file__))
        )
    )
)
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

try:
    from _constants import hybrid_v4_output_dir
except Exception as exc:  # pragma: no cover
    raise RuntimeError(
        "Could not import hybrid_v4_output_dir from _constants.py. "
        "Run from the project root or check PROJECT_ROOT handling."
    ) from exc

EPS = 1e-9
TASKS = ("gender", "occupation")

SEMANTIC_DIR = Path(hybrid_v4_output_dir) / "error_analysis" / "semantic_signals"
OUTPUT_DIR = Path(hybrid_v4_output_dir) / "error_analysis" / "synthetic_semantic_features"


def safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if value is None:
            return default
        return float(value)
    except (TypeError, ValueError):
        return default


def ratio(a: float, b: float) -> float:
    return a / (b + EPS)


def clip(value: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, value))


def log1p_pos(value: float) -> float:
    return math.log1p(max(0.0, value))


def sigmoid_like(value: float) -> float:
    # Monotonic bounded transform; useful for very spiky ratio scores.
    return value / (1.0 + abs(value)) if value != 0 else 0.0


def mean(values: Sequence[float]) -> float:
    return sum(values) / len(values) if values else 0.0


def stdev(values: Sequence[float]) -> float:
    if len(values) < 2:
        return 0.0
    return statistics.pstdev(values)


def cohen_d(a: Sequence[float], b: Sequence[float]) -> float:
    if not a or not b:
        return 0.0
    ma, mb = mean(a), mean(b)
    va = statistics.pvariance(a) if len(a) > 1 else 0.0
    vb = statistics.pvariance(b) if len(b) > 1 else 0.0
    pooled = math.sqrt((va + vb) / 2.0)
    return 0.0 if pooled <= EPS else (ma - mb) / pooled


def macro_f1(y_true: Sequence[str], y_pred: Sequence[str]) -> float:
    labels = sorted(set(y_true) | set(y_pred))
    if not labels:
        return 0.0
    f1s: List[float] = []
    for label in labels:
        tp = sum(1 for t, p in zip(y_true, y_pred) if t == label and p == label)
        fp = sum(1 for t, p in zip(y_true, y_pred) if t != label and p == label)
        fn = sum(1 for t, p in zip(y_true, y_pred) if t == label and p != label)
        precision = tp / (tp + fp) if (tp + fp) else 0.0
        recall = tp / (tp + fn) if (tp + fn) else 0.0
        f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) else 0.0
        f1s.append(f1)
    return mean(f1s)


def accuracy(y_true: Sequence[str], y_pred: Sequence[str]) -> float:
    return sum(1 for t, p in zip(y_true, y_pred) if t == p) / len(y_true) if y_true else 0.0


def load_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def flatten_top_examples(report: Dict[str, Any]) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    seen: set[str] = set()
    for examples in report.get("top_examples", {}).values():
        if not isinstance(examples, list):
            continue
        for row in examples:
            cid = str(row.get("celebrity_id", ""))
            if cid and cid not in seen:
                rows.append(row)
                seen.add(cid)
    return rows


def load_profiles(task: str) -> Tuple[List[Dict[str, Any]], Path, str]:
    path = SEMANTIC_DIR / f"{task}_semantic_signal_report.json"
    report = load_json(path)
    rows = report.get("profiles")
    source = "profiles"
    if not isinstance(rows, list) or not rows:
        rows = report.get("profile_rows")
        source = "profile_rows"
    if not isinstance(rows, list) or not rows:
        rows = flatten_top_examples(report)
        source = "top_examples_fallback"
    if not rows:
        raise ValueError(
            f"No profile rows found in {path}. Re-run semantic signal analysis with full profiles output."
        )
    clean_rows: List[Dict[str, Any]] = []
    for row in rows:
        if not isinstance(row, dict):
            continue
        true_label = row.get("true_label") or row.get("true") or row.get("gold")
        pred_label = row.get("pred_label") or row.get("prediction") or row.get("pred")
        cid = row.get("celebrity_id") or row.get("id") or row.get("profile_id")
        if true_label is None or pred_label is None or cid is None:
            continue
        row = dict(row)
        row["celebrity_id"] = str(cid)
        row["true_label"] = str(true_label)
        row["pred_label"] = str(pred_label)
        row["group"] = row.get("group") or make_group(row["true_label"], row["pred_label"])
        row.setdefault("signal_values", {})
        row.setdefault("top_keyword_hits", [])
        clean_rows.append(row)
    return clean_rows, path, source


def make_group(true_label: str, pred_label: str) -> str:
    if true_label == pred_label:
        return f"correct_{true_label}"
    return f"{true_label}_to_{pred_label}"


def signal(row: Dict[str, Any], name: str) -> float:
    return safe_float(row.get("signal_values", {}).get(name, 0.0))


def add_synthetic_features(task: str, row: Dict[str, Any]) -> Dict[str, float]:
    if task == "gender":
        family = signal(row, "family_signal")
        relationship = signal(row, "relationship_signal")
        female_role = signal(row, "female_role_signal")
        violence = signal(row, "violence_against_women_signal")
        social = signal(row, "emotion_social_issue_signal")
        male_role = signal(row, "male_role_signal")

        female_context = family + relationship + female_role + violence
        social_context = violence + social
        role_balance = female_role - male_role
        relationship_balance = relationship - male_role
        family_balance = family - male_role

        features = {
            # Existing strong ratios / differences.
            "relationship_minus_male_role": relationship_balance,
            "female_minus_male_role": role_balance,
            "family_minus_male_role": family_balance,
            "female_context_minus_male_role": female_context - male_role,
            "violence_social_combo": social_context,
            # New synthetic higher-order features.
            "relationship_dominance_index": relationship_balance / (relationship + male_role + 1.0),
            "female_role_dominance_index": role_balance / (female_role + male_role + 1.0),
            "female_context_density": female_context / (female_context + male_role + social + 1.0),
            "relationship_share_of_context": relationship / (female_context + male_role + social + 1.0),
            "female_uncertainty_pressure": relationship_balance + 0.5 * role_balance + 0.25 * family_balance,
            "female_context_pressure": relationship_balance + role_balance + family_balance + 0.5 * social_context,
            "bounded_relationship_pressure": sigmoid_like(relationship_balance),
            "log_relationship_advantage": log1p_pos(relationship_balance),
            "low_relationship_male_pressure": male_role - relationship,
        }
        return features

    if task == "occupation":
        creator = signal(row, "creator_signal")
        performer = signal(row, "performer_signal")
        sports = signal(row, "sports_signal")
        politics = signal(row, "politics_signal")
        business = signal(row, "business_branding_signal")
        fan = signal(row, "fan_community_signal")

        performer_adv = performer - creator
        fan_adv = fan - creator
        sports_adv = sports - performer
        politics_adv = politics - creator
        creator_adv = creator - max(performer, sports, politics, fan)
        entertainer_pressure = performer + fan - creator
        politics_pressure = politics + 0.25 * fan - creator
        sports_pressure = sports - 0.5 * performer + 0.25 * fan - creator
        creator_recovery_pressure = creator - performer - fan

        features = {
            # Existing ratios / differences.
            "performer_minus_creator": performer_adv,
            "fan_minus_creator": fan_adv,
            "performer_fan_minus_creator": entertainer_pressure,
            "sports_minus_performer": sports_adv,
            "politics_minus_creator": politics_adv,
            # New synthetic higher-order features.
            "performer_dominance_index": performer_adv / (performer + creator + 1.0),
            "fan_dominance_index": fan_adv / (fan + creator + 1.0),
            "entertainer_pressure_index": entertainer_pressure / (performer + fan + creator + 1.0),
            "politics_dominance_index": politics_adv / (politics + creator + 1.0),
            "sports_dominance_index": sports_adv / (sports + performer + 1.0),
            "creator_residual_strength": creator_adv,
            "creator_recovery_pressure": creator_recovery_pressure,
            "politics_recovery_pressure": politics_pressure,
            "sports_recovery_pressure": sports_pressure,
            "bounded_politics_pressure": sigmoid_like(politics_adv),
            "bounded_sports_pressure": sigmoid_like(sports_adv),
            "bounded_creator_recovery": sigmoid_like(creator_recovery_pressure),
            "business_creator_support": business + creator - performer,
        }
        return features

    raise ValueError(f"Unsupported task: {task}")


def feature_definitions(task: str) -> Dict[str, str]:
    if task == "gender":
        return {
            "relationship_minus_male_role": "relationship_signal - male_role_signal",
            "female_minus_male_role": "female_role_signal - male_role_signal",
            "family_minus_male_role": "family_signal - male_role_signal",
            "female_context_minus_male_role": "family + relationship + female_role + violence - male_role",
            "violence_social_combo": "violence_against_women_signal + emotion_social_issue_signal",
            "relationship_dominance_index": "relationship-minus-male normalized by relationship + male_role + 1",
            "female_role_dominance_index": "female-minus-male-role normalized by female_role + male_role + 1",
            "female_context_density": "female_context / (female_context + male_role + social + 1)",
            "relationship_share_of_context": "relationship / (female_context + male_role + social + 1)",
            "female_uncertainty_pressure": "relationship_minus_male + 0.5*female_minus_male + 0.25*family_minus_male",
            "female_context_pressure": "relationship_minus_male + female_minus_male + family_minus_male + 0.5*violence_social_combo",
            "bounded_relationship_pressure": "bounded transform of relationship_minus_male_role",
            "log_relationship_advantage": "log1p(max(0, relationship_minus_male_role))",
            "low_relationship_male_pressure": "male_role_signal - relationship_signal",
        }
    return {
        "performer_minus_creator": "performer_signal - creator_signal",
        "fan_minus_creator": "fan_community_signal - creator_signal",
        "performer_fan_minus_creator": "performer_signal + fan_community_signal - creator_signal",
        "sports_minus_performer": "sports_signal - performer_signal",
        "politics_minus_creator": "politics_signal - creator_signal",
        "performer_dominance_index": "performer-minus-creator normalized by performer + creator + 1",
        "fan_dominance_index": "fan-minus-creator normalized by fan + creator + 1",
        "entertainer_pressure_index": "performer+fan-creator normalized by performer + fan + creator + 1",
        "politics_dominance_index": "politics-minus-creator normalized by politics + creator + 1",
        "sports_dominance_index": "sports-minus-performer normalized by sports + performer + 1",
        "creator_residual_strength": "creator_signal - max(performer, sports, politics, fan)",
        "creator_recovery_pressure": "creator_signal - performer_signal - fan_community_signal",
        "politics_recovery_pressure": "politics_signal + 0.25*fan_community_signal - creator_signal",
        "sports_recovery_pressure": "sports_signal - 0.5*performer_signal + 0.25*fan_community_signal - creator_signal",
        "bounded_politics_pressure": "bounded transform of politics_minus_creator",
        "bounded_sports_pressure": "bounded transform of sports_minus_performer",
        "bounded_creator_recovery": "bounded transform of creator_recovery_pressure",
        "business_creator_support": "business_branding_signal + creator_signal - performer_signal",
    }


def enrich_rows(task: str, rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for row in rows:
        row = dict(row)
        row["synthetic_features"] = add_synthetic_features(task, row)
        row["group"] = make_group(row["true_label"], row["pred_label"])
        out.append(row)
    return out


def group_stats(rows: List[Dict[str, Any]], feature_names: Sequence[str]) -> Dict[str, Dict[str, float]]:
    grouped: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for row in rows:
        grouped[row["group"]].append(row)
    stats: Dict[str, Dict[str, float]] = {}
    for group, members in sorted(grouped.items()):
        item: Dict[str, float] = {"n": float(len(members))}
        for feat in feature_names:
            item[feat] = mean([safe_float(m["synthetic_features"].get(feat)) for m in members])
        stats[group] = item
    return stats


def compare_groups(rows: List[Dict[str, Any]], feature_names: Sequence[str], comparisons: Sequence[Tuple[str, str]]) -> Dict[str, List[Dict[str, float]]]:
    grouped: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for row in rows:
        grouped[row["group"]].append(row)
    out: Dict[str, List[Dict[str, float]]] = {}
    for a, b in comparisons:
        if a not in grouped or b not in grouped:
            continue
        entries = []
        for feat in feature_names:
            av = [safe_float(r["synthetic_features"].get(feat)) for r in grouped[a]]
            bv = [safe_float(r["synthetic_features"].get(feat)) for r in grouped[b]]
            entries.append({
                "feature": feat,
                "mean_a": mean(av),
                "mean_b": mean(bv),
                "diff": mean(av) - mean(bv),
                "cohen_d": cohen_d(av, bv),
            })
        entries.sort(key=lambda x: abs(x["cohen_d"]), reverse=True)
        out[f"{a} vs {b}"] = entries
    return out


def default_comparisons(task: str) -> List[Tuple[str, str]]:
    if task == "gender":
        return [
            ("female_to_male", "correct_male"),
            ("female_to_male", "correct_female"),
            ("male_to_female", "correct_female"),
            ("male_to_female", "correct_male"),
        ]
    return [
        ("creator_to_performer", "correct_creator"),
        ("creator_to_performer", "correct_performer"),
        ("creator_to_politics", "correct_creator"),
        ("creator_to_sports", "correct_creator"),
        ("sports_to_performer", "correct_sports"),
        ("sports_to_performer", "correct_performer"),
        ("politics_to_creator", "correct_politics"),
        ("politics_to_creator", "correct_creator"),
    ]


def top_examples(rows: List[Dict[str, Any]], task: str) -> Dict[str, Dict[str, List[Dict[str, Any]]]]:
    if task == "gender":
        groups_features = {
            "female_to_male": ["relationship_dominance_index", "female_uncertainty_pressure", "female_context_pressure"],
            "male_to_female": ["relationship_dominance_index", "female_uncertainty_pressure", "low_relationship_male_pressure"],
        }
    else:
        groups_features = {
            "creator_to_performer": ["creator_recovery_pressure", "business_creator_support", "entertainer_pressure_index"],
            "creator_to_politics": ["politics_recovery_pressure", "politics_dominance_index"],
            "creator_to_sports": ["sports_recovery_pressure", "sports_dominance_index"],
            "sports_to_performer": ["sports_recovery_pressure", "sports_dominance_index", "entertainer_pressure_index"],
            "politics_to_creator": ["politics_recovery_pressure", "politics_dominance_index"],
        }
    out: Dict[str, Dict[str, List[Dict[str, Any]]]] = {}
    for group, feats in groups_features.items():
        members = [r for r in rows if r["group"] == group]
        if not members:
            continue
        out[group] = {}
        for feat in feats:
            reverse = not feat.startswith("creator_recovery") and feat != "business_creator_support"
            # For creator recovery, high positive means more creator-like; for entertainer index high means performer-like.
            if feat in {"creator_recovery_pressure", "business_creator_support"}:
                reverse = True
            ranked = sorted(members, key=lambda r: safe_float(r["synthetic_features"].get(feat)), reverse=reverse)[:10]
            out[group][feat] = [compact_example(r, [feat]) for r in ranked]
    return out


def compact_hits(row: Dict[str, Any], limit: int = 8) -> str:
    hits = row.get("top_keyword_hits") or []
    parts: List[str] = []
    for item in hits[:limit]:
        if isinstance(item, (list, tuple)) and len(item) >= 2:
            parts.append(f"{item[0]}:{item[1]}")
    return ", ".join(parts)


def compact_example(row: Dict[str, Any], feature_names: Sequence[str]) -> Dict[str, Any]:
    return {
        "celebrity_id": row.get("celebrity_id"),
        "true_label": row.get("true_label"),
        "pred_label": row.get("pred_label"),
        "group": row.get("group"),
        "token_count": int(safe_float(row.get("token_count", 0))),
        "features": {f: safe_float(row.get("synthetic_features", {}).get(f)) for f in feature_names},
        "top_keyword_hits": row.get("top_keyword_hits", [])[:8],
    }


class Rule:
    def __init__(self, name: str, description: str, from_label: str, to_label: str, condition: Callable[[Dict[str, Any]], bool]):
        self.name = name
        self.description = description
        self.from_label = from_label
        self.to_label = to_label
        self.condition = condition


def synthetic_rules(task: str) -> List[Rule]:
    if task == "gender":
        return [
            Rule(
                "female_from_male_relationship_dominance_0p35",
                "pred=male and normalized relationship dominance is high -> female",
                "male",
                "female",
                lambda r: r["pred_label"] == "male" and r["synthetic_features"].get("relationship_dominance_index", 0.0) >= 0.35,
            ),
            Rule(
                "female_from_male_uncertainty_pressure_2p4",
                "pred=male and combined female uncertainty pressure is high -> female",
                "male",
                "female",
                lambda r: r["pred_label"] == "male" and r["synthetic_features"].get("female_uncertainty_pressure", 0.0) >= 2.4,
            ),
            Rule(
                "male_from_female_low_relationship_dominance_neg0p05",
                "pred=female and relationship dominance is negative -> male",
                "female",
                "male",
                lambda r: r["pred_label"] == "female" and r["synthetic_features"].get("relationship_dominance_index", 0.0) <= -0.05,
            ),
        ]
    return [
        Rule(
            "politics_from_creator_politics_recovery_4p8",
            "pred=creator and synthetic politics recovery pressure is high -> politics",
            "creator",
            "politics",
            lambda r: r["pred_label"] == "creator" and r["synthetic_features"].get("politics_recovery_pressure", 0.0) >= 4.8,
        ),
        Rule(
            "creator_from_performer_creator_recovery_neg1p2",
            "pred=performer and creator recovery pressure is not strongly negative -> creator",
            "performer",
            "creator",
            lambda r: r["pred_label"] == "performer" and r["synthetic_features"].get("creator_recovery_pressure", 0.0) >= -1.2,
        ),
        Rule(
            "sports_from_performer_sports_recovery_1p5",
            "pred=performer and synthetic sports recovery pressure is high -> sports",
            "performer",
            "sports",
            lambda r: r["pred_label"] == "performer" and r["synthetic_features"].get("sports_recovery_pressure", 0.0) >= 1.5,
        ),
        Rule(
            "avoid_performer_when_entertainer_index_low_0p45",
            "pred=performer, creator recovery pressure high and entertainer pressure index low -> creator",
            "performer",
            "creator",
            lambda r: (
                r["pred_label"] == "performer"
                and r["synthetic_features"].get("creator_recovery_pressure", 0.0) >= -1.0
                and r["synthetic_features"].get("entertainer_pressure_index", 0.0) <= 0.45
            ),
        ),
    ]


def apply_rule(rows: List[Dict[str, Any]], rule: Rule) -> Dict[str, Any]:
    y_true = [r["true_label"] for r in rows]
    y_pred_before = [r["pred_label"] for r in rows]
    y_pred_after = list(y_pred_before)
    changed_examples: List[Dict[str, Any]] = []
    changed = improved = harmed = still_wrong = 0

    for i, row in enumerate(rows):
        if not rule.condition(row):
            continue
        old = row["pred_label"]
        if old != rule.from_label:
            continue
        new = rule.to_label
        if new == old:
            continue
        y_pred_after[i] = new
        changed += 1
        was_correct = old == row["true_label"]
        now_correct = new == row["true_label"]
        if (not was_correct) and now_correct:
            improved += 1
        elif was_correct and (not now_correct):
            harmed += 1
        elif not now_correct:
            still_wrong += 1
        ex = dict(row)
        ex["old_pred"] = old
        ex["new_pred"] = new
        ex["improved"] = (not was_correct) and now_correct
        ex["harmed"] = was_correct and (not now_correct)
        changed_examples.append(ex)

    before_acc = accuracy(y_true, y_pred_before)
    after_acc = accuracy(y_true, y_pred_after)
    before_f1 = macro_f1(y_true, y_pred_before)
    after_f1 = macro_f1(y_true, y_pred_after)
    local_before = 0.0
    local_after = 0.0
    if changed:
        local_true = [r["true_label"] for r in changed_examples]
        local_old = [r["old_pred"] for r in changed_examples]
        local_new = [r["new_pred"] for r in changed_examples]
        local_before = accuracy(local_true, local_old)
        local_after = accuracy(local_true, local_new)

    return {
        "rule": rule.name,
        "description": rule.description,
        "change": f"{rule.from_label} -> {rule.to_label}",
        "changed": changed,
        "improved": improved,
        "harmed": harmed,
        "still_wrong": still_wrong,
        "global_delta_acc": after_acc - before_acc,
        "global_delta_macro_f1": after_f1 - before_f1,
        "global_after_acc": after_acc,
        "global_after_macro_f1": after_f1,
        "local_before_acc": local_before,
        "local_after_acc": local_after,
        "examples": [compact_rule_example(r) for r in changed_examples[:30]],
    }


def compact_rule_example(row: Dict[str, Any]) -> Dict[str, Any]:
    interesting = [
        "relationship_dominance_index",
        "female_uncertainty_pressure",
        "female_context_pressure",
        "politics_recovery_pressure",
        "sports_recovery_pressure",
        "creator_recovery_pressure",
        "entertainer_pressure_index",
        "business_creator_support",
    ]
    feats = row.get("synthetic_features", {})
    return {
        "celebrity_id": row.get("celebrity_id"),
        "true_label": row.get("true_label"),
        "old_pred": row.get("old_pred"),
        "new_pred": row.get("new_pred"),
        "improved": row.get("improved"),
        "harmed": row.get("harmed"),
        "token_count": int(safe_float(row.get("token_count", 0))),
        "features": {k: safe_float(feats.get(k)) for k in interesting if k in feats},
        "top_keyword_hits": row.get("top_keyword_hits", [])[:8],
    }


def simulate_rules(task: str, rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    y_true = [r["true_label"] for r in rows]
    y_pred = [r["pred_label"] for r in rows]
    baseline = {
        "n": len(rows),
        "accuracy": accuracy(y_true, y_pred),
        "macro_f1": macro_f1(y_true, y_pred),
    }
    results = [apply_rule(rows, rule) for rule in synthetic_rules(task)]
    return {"baseline": baseline, "rule_results": results}


def fmt(value: Any, digits: int = 4) -> str:
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def write_markdown(task: str, analysis: Dict[str, Any], path: Path) -> None:
    lines: List[str] = []
    lines.append(f"# Synthetic Semantic Feature Analysis: {task}\n")
    lines.append("> Diagnostic post-hoc analysis on existing HybridV4 predictions. Do not report rule results as final tuned test performance.\n")
    lines.append(f"Script version: `{SCRIPT_VERSION}`\n")
    lines.append(f"Source semantic report: `{analysis['source_report']}`\n")
    lines.append(f"Profile row source: `{analysis['row_source']}`\n")
    lines.append(f"Profiles: **{analysis['n_profiles']}**\n")

    lines.append("## Synthetic feature definitions\n")
    lines.append("| feature | definition |")
    lines.append("| --- | --- |")
    for feat, desc in analysis["feature_definitions"].items():
        lines.append(f"| `{feat}` | {desc} |")
    lines.append("")

    lines.append("## Group means\n")
    feature_names = analysis["feature_names"]
    header = "| group | n | " + " | ".join(feature_names) + " |"
    sep = "| --- | ---: | " + " | ".join(["---:"] * len(feature_names)) + " |"
    lines.extend([header, sep])
    for group, stats in analysis["group_stats"].items():
        vals = [fmt(stats.get(f, 0.0)) for f in feature_names]
        lines.append(f"| `{group}` | {int(stats['n'])} | " + " | ".join(vals) + " |")
    lines.append("")

    lines.append("## Group comparisons\n")
    for name, entries in analysis["comparisons"].items():
        lines.append(f"### `{name}`\n")
        lines.append("| feature | mean A | mean B | A - B | approx. Cohen d |")
        lines.append("| --- | ---: | ---: | ---: | ---: |")
        for e in entries[:12]:
            lines.append(
                f"| `{e['feature']}` | {fmt(e['mean_a'])} | {fmt(e['mean_b'])} | {fmt(e['diff'])} | {fmt(e['cohen_d'])} |"
            )
        lines.append("")

    lines.append("## Synthetic rule simulation\n")
    baseline = analysis["simulation"]["baseline"]
    lines.append("### Global baseline\n")
    lines.append("| n | accuracy | macro_f1 |")
    lines.append("| ---: | ---: | ---: |")
    lines.append(f"| {baseline['n']} | {fmt(baseline['accuracy'])} | {fmt(baseline['macro_f1'])} |\n")

    lines.append("### Rule results\n")
    lines.append("| rule | change | changed | improved | harmed | still wrong | global Δacc | global Δmacro-F1 | local before acc | local after acc |")
    lines.append("| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
    for r in analysis["simulation"]["rule_results"]:
        lines.append(
            f"| `{r['rule']}` | {r['change']} | {r['changed']} | {r['improved']} | {r['harmed']} | {r['still_wrong']} | "
            f"{fmt(r['global_delta_acc'])} | {fmt(r['global_delta_macro_f1'])} | {fmt(r['local_before_acc'])} | {fmt(r['local_after_acc'])} |"
        )
    lines.append("")

    lines.append("## Changed examples by synthetic rule\n")
    for r in analysis["simulation"]["rule_results"]:
        lines.append(f"### `{r['rule']}`\n")
        lines.append(r["description"] + "\n")
        examples = r.get("examples", [])
        if not examples:
            lines.append("No changed profiles.\n")
            continue
        lines.append("| id | true | old pred | new pred | improved | harmed | tokens | synthetic features | top keyword hits |")
        lines.append("| --- | --- | --- | --- | ---: | ---: | ---: | --- | --- |")
        for ex in examples[:20]:
            feat_text = ", ".join(f"{k}={fmt(v, 2)}" for k, v in ex.get("features", {}).items())
            hit_text = ", ".join(f"{h[0]}:{h[1]}" for h in ex.get("top_keyword_hits", []) if isinstance(h, (list, tuple)) and len(h) >= 2)
            lines.append(
                f"| {ex['celebrity_id']} | {ex['true_label']} | {ex['old_pred']} | {ex['new_pred']} | "
                f"{ex['improved']} | {ex['harmed']} | {ex['token_count']} | {feat_text} | {hit_text} |"
            )
        lines.append("")

    lines.append("## Top examples by synthetic feature\n")
    for group, by_feat in analysis["top_examples"].items():
        lines.append(f"### `{group}`\n")
        for feat, examples in by_feat.items():
            lines.append(f"#### Ranking by `{feat}`\n")
            lines.append("| id | true | pred | tokens | value | top keyword hits |")
            lines.append("| --- | --- | --- | ---: | ---: | --- |")
            for ex in examples[:10]:
                value = list(ex["features"].values())[0] if ex.get("features") else 0.0
                hit_text = ", ".join(f"{h[0]}:{h[1]}" for h in ex.get("top_keyword_hits", []) if isinstance(h, (list, tuple)) and len(h) >= 2)
                lines.append(
                    f"| {ex['celebrity_id']} | {ex['true_label']} | {ex['pred_label']} | {ex['token_count']} | {fmt(value)} | {hit_text} |"
                )
            lines.append("")

    lines.append("## Interpretation note\n")
    if task == "gender":
        lines.append(
            "Synthetic gender features reinforce the finding that relationship-oriented follower language is an uncertainty signal. "
            "The features can highlight specific cases, but rule effects should remain diagnostic unless validated on a separate split."
        )
    else:
        lines.append(
            "Synthetic occupation features are most useful for targeted recovery directions: politics-from-creator, sports-from-performer, "
            "and selective creator-from-performer. Because this is post-hoc on test predictions, the results motivate validation-based meta-features rather than final rules."
        )
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def analyze_task(task: str) -> Dict[str, Any]:
    rows, source_path, row_source = load_profiles(task)
    rows = enrich_rows(task, rows)
    defs = feature_definitions(task)
    feature_names = list(defs.keys())
    analysis = {
        "task": task,
        "script_version": SCRIPT_VERSION,
        "source_report": str(source_path),
        "row_source": row_source,
        "n_profiles": len(rows),
        "feature_definitions": defs,
        "feature_names": feature_names,
        "group_stats": group_stats(rows, feature_names),
        "comparisons": compare_groups(rows, feature_names, default_comparisons(task)),
        "top_examples": top_examples(rows, task),
        "simulation": simulate_rules(task, rows),
    }
    return analysis


def write_summary(results: Dict[str, Dict[str, Any]], path: Path) -> None:
    lines: List[str] = []
    lines.append("# Synthetic Semantic Feature Analysis Summary\n")
    lines.append(f"Script version: `{SCRIPT_VERSION}`\n")
    lines.append("> Post-hoc diagnostic analysis on existing HybridV4 predictions. Do not report rule results as final tuned test performance.\n")
    for task, analysis in results.items():
        baseline = analysis["simulation"]["baseline"]
        lines.append(f"## {task}\n")
        lines.append(f"Rows loaded: **{analysis['n_profiles']}** from `{analysis['row_source']}`.\n")
        lines.append(f"Global baseline accuracy: **{baseline['accuracy']:.4f}**, macro-F1: **{baseline['macro_f1']:.4f}**.\n")
        lines.append("| rule | changed | improved | harmed | global Δaccuracy | global Δmacro-F1 | local before acc | local after acc |")
        lines.append("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
        for r in analysis["simulation"]["rule_results"]:
            lines.append(
                f"| `{r['rule']}` | {r['changed']} | {r['improved']} | {r['harmed']} | "
                f"{r['global_delta_acc']:+.4f} | {r['global_delta_macro_f1']:+.4f} | {r['local_before_acc']:.4f} | {r['local_after_acc']:.4f} |"
            )
        lines.append("")
    lines.append("## Suggested thesis wording\n")
    lines.append(
        "Synthetic semantic features combine raw keyword signals into normalized dominance and pressure indicators. "
        "They provide additional explanatory evidence for HybridV4 errors and help identify small subsets of plausibly correctable cases. "
        "Because the rules are simulated post hoc on existing test predictions, they should be treated as diagnostic probes and as motivation for future validation-based meta-models, not as final optimized test results."
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyze synthetic semantic features for HybridV4 error analysis.")
    parser.add_argument("--task", choices=TASKS, default=None, help="Run only one task. Defaults to both.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    tasks = [args.task] if args.task else list(TASKS)
    results: Dict[str, Dict[str, Any]] = {}
    print(f"[INFO] Running {SCRIPT_VERSION}")
    print(f"[INFO] Semantic report dir: {SEMANTIC_DIR}")
    print(f"[INFO] Output dir: {OUTPUT_DIR}")
    for task in tasks:
        print(f"\n========== {task} ==========")
        analysis = analyze_task(task)
        results[task] = analysis
        json_path = OUTPUT_DIR / f"{task}_synthetic_semantic_features.json"
        md_path = OUTPUT_DIR / f"{task}_synthetic_semantic_features.md"
        json_path.write_text(json.dumps(analysis, indent=2, ensure_ascii=False), encoding="utf-8")
        write_markdown(task, analysis, md_path)
        print(f"[INFO] Rows loaded: {analysis['n_profiles']} from {analysis['row_source']}")
        print(f"[INFO] Wrote {md_path}")
        print(f"[INFO] Wrote {json_path}")
    if len(results) > 1:
        summary_path = OUTPUT_DIR / "synthetic_semantic_features_summary.md"
        write_summary(results, summary_path)
        print(f"[INFO] Wrote {summary_path}")


if __name__ == "__main__":
    main()
