"""
Semantic correction rule simulation for HybridV4.

This script is diagnostic error analysis only. It evaluates simple post-hoc
semantic correction rules on all loaded profile rows, not only on top examples.

Run from project root:
    python -m Models.HybridV4.analysis.simulate_semantic_correction_rules
"""

import argparse
import json
import os
import sys
from collections import Counter, defaultdict
from copy import deepcopy
from typing import Any, Dict, List, Optional, Tuple

SCRIPT_VERSION = "semantic-rule-simulation-v2-global-baseline"

PROJECT_ROOT = os.path.dirname(
    os.path.dirname(
        os.path.dirname(
            os.path.dirname(os.path.abspath(__file__))
        )
    )
)
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

try:
    from _constants import hybrid_v4_output_dir
except ImportError as exc:
    raise ImportError(
        "Could not import hybrid_v4_output_dir from _constants.py. "
        "Run this module from the project root."
    ) from exc

INPUT_DIR = os.path.join(hybrid_v4_output_dir, "error_analysis", "semantic_signals")
OUTPUT_DIR = os.path.join(hybrid_v4_output_dir, "error_analysis", "semantic_rule_simulation")

TASK_FILES = {
    "gender": "gender_semantic_signal_report.json",
    "occupation": "occupation_semantic_signal_report.json",
}

LABELS = {
    "gender": ["female", "male"],
    "occupation": ["creator", "performer", "politics", "sports"],
}


def read_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def safe_float(x: Any, default: float = 0.0) -> float:
    try:
        if x is None:
            return default
        return float(x)
    except (TypeError, ValueError):
        return default


def profile_id(row: Dict[str, Any]) -> str:
    for key in ["celebrity_id", "id", "profile_id"]:
        if key in row:
            return str(row[key])
    return ""


def true_label(row: Dict[str, Any]) -> str:
    for key in ["true_label", "gold_label", "label", "true"]:
        if key in row:
            return str(row[key])
    return ""


def pred_label(row: Dict[str, Any]) -> str:
    for key in ["pred_label", "fusion_pred_label", "prediction", "predicted_label", "pred"]:
        if key in row:
            return str(row[key])
    return ""


def token_count(row: Dict[str, Any]) -> int:
    for key in ["token_count", "tokens", "n_tokens"]:
        if key in row:
            try:
                return int(row[key])
            except (TypeError, ValueError):
                pass
    return 0


def signal_values(row: Dict[str, Any]) -> Dict[str, float]:
    values = row.get("signal_values", {})
    if not isinstance(values, dict):
        values = {}
    return {k: safe_float(v) for k, v in values.items()}


def top_hits(row: Dict[str, Any], max_items: int = 8) -> str:
    hits = row.get("top_keyword_hits", [])
    out = []
    if isinstance(hits, list):
        for item in hits[:max_items]:
            if isinstance(item, (list, tuple)) and len(item) >= 2:
                out.append(f"{item[0]}:{item[1]}")
            elif isinstance(item, dict):
                token = item.get("token") or item.get("keyword")
                count = item.get("count") or item.get("value")
                if token is not None and count is not None:
                    out.append(f"{token}:{count}")
    return ", ".join(out)


def load_profile_rows(report: Dict[str, Any]) -> Tuple[List[Dict[str, Any]], str]:
    """
    Load full profile rows from a semantic signal report.

    v2 intentionally avoids using top_examples as the primary source because that
    produces partial baselines such as n=40 or n=79. Full reports generated by
    analyze_semantic_error_signals.py should contain one of the full-row keys
    below. If an older report lacks them, we fall back to top_examples and mark
    the source explicitly in the output.
    """
    full_keys = [
        "profiles",
        "profile_rows",
        "rows",
        "all_profiles",
        "analysis_rows",
        "examples_all",
    ]
    for key in full_keys:
        rows = report.get(key)
        if isinstance(rows, list) and rows:
            return rows, key

    # Backward-compatible fallback only. This is not suitable for global metrics.
    top = report.get("top_examples", {})
    if isinstance(top, dict):
        dedup: Dict[str, Dict[str, Any]] = {}
        for examples in top.values():
            if isinstance(examples, list):
                for row in examples:
                    if isinstance(row, dict):
                        cid = profile_id(row)
                        if cid:
                            dedup[cid] = row
        if dedup:
            return list(dedup.values()), "top_examples_fallback_partial"

    raise ValueError(
        "No profile rows found in semantic signal report. Regenerate the semantic "
        "signal reports with a version that stores full profile rows under "
        "`profiles` or `profile_rows`."
    )


def add_ratio_features(row: Dict[str, Any], task: str) -> Dict[str, Any]:
    row = deepcopy(row)
    sig = signal_values(row)
    ratios: Dict[str, float] = {}

    if task == "gender":
        female = sig.get("female_role_signal", 0.0)
        male = sig.get("male_role_signal", 0.0)
        relationship = sig.get("relationship_signal", 0.0)
        family = sig.get("family_signal", 0.0)
        violence = sig.get("violence_against_women_signal", 0.0)
        social = sig.get("emotion_social_issue_signal", 0.0)
        ratios = {
            "female_minus_male_role": female - male,
            "relationship_minus_male_role": relationship - male,
            "family_minus_male_role": family - male,
            "female_context_minus_male_role": family + relationship + female + violence - male,
            "violence_social_combo": violence + social,
        }
    elif task == "occupation":
        creator = sig.get("creator_signal", 0.0)
        performer = sig.get("performer_signal", 0.0)
        sports = sig.get("sports_signal", 0.0)
        politics = sig.get("politics_signal", 0.0)
        fan = sig.get("fan_community_signal", 0.0)
        ratios = {
            "performer_minus_creator": performer - creator,
            "creator_minus_performer": creator - performer,
            "fan_minus_creator": fan - creator,
            "performer_fan_minus_creator": performer + fan - creator,
            "sports_minus_performer": sports - performer,
            "politics_minus_creator": politics - creator,
        }

    row["ratio_features"] = ratios
    return row


def macro_f1(y_true: List[str], y_pred: List[str], labels: List[str]) -> float:
    scores = []
    for lab in labels:
        tp = sum(1 for t, p in zip(y_true, y_pred) if t == lab and p == lab)
        fp = sum(1 for t, p in zip(y_true, y_pred) if t != lab and p == lab)
        fn = sum(1 for t, p in zip(y_true, y_pred) if t == lab and p != lab)
        precision = tp / (tp + fp) if (tp + fp) else 0.0
        recall = tp / (tp + fn) if (tp + fn) else 0.0
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
        scores.append(f1)
    return sum(scores) / len(scores) if scores else 0.0


def metrics(rows: List[Dict[str, Any]], pred_key: str = "_sim_pred") -> Dict[str, float]:
    y_true = [true_label(r) for r in rows]
    y_pred = [str(r.get(pred_key, pred_label(r))) for r in rows]
    labels = sorted(set(y_true) | set(y_pred))
    correct = sum(1 for t, p in zip(y_true, y_pred) if t == p)
    return {
        "n": len(rows),
        "accuracy": correct / len(rows) if rows else 0.0,
        "macro_f1": macro_f1(y_true, y_pred, labels),
    }


def base_rows(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    out = []
    for row in rows:
        r = deepcopy(row)
        r["_sim_pred"] = pred_label(r)
        out.append(r)
    return out


def rule_applies(row: Dict[str, Any], task: str, rule_name: str) -> bool:
    pred = pred_label(row)
    rf = row.get("ratio_features", {})

    if task == "gender":
        if rule_name == "female_flag_from_male_high_relationship_minus_male_2p0":
            return pred == "male" and rf.get("relationship_minus_male_role", 0.0) >= 2.0
        if rule_name == "female_flag_from_male_high_female_context_7p0":
            return pred == "male" and rf.get("female_context_minus_male_role", 0.0) >= 7.0
        if rule_name == "male_flag_from_female_low_relationship_minus_male_0p8":
            return pred == "female" and rf.get("relationship_minus_male_role", 0.0) <= 0.8

    if task == "occupation":
        if rule_name == "politics_recover_from_creator_high_politics_minus_creator_4p5":
            return pred == "creator" and rf.get("politics_minus_creator", 0.0) >= 4.5
        if rule_name == "politics_recover_from_creator_high_politics_minus_creator_6p0":
            return pred == "creator" and rf.get("politics_minus_creator", 0.0) >= 6.0
        if rule_name == "creator_recover_from_performer_low_performer_advantage":
            return (
                pred == "performer"
                and rf.get("performer_minus_creator", 0.0) <= 0.6
                and rf.get("fan_minus_creator", 0.0) <= 0.0
            )
        if rule_name == "sports_recover_from_performer_high_sports_minus_performer_2p0":
            return pred == "performer" and rf.get("sports_minus_performer", 0.0) >= 2.0

    return False


def new_label_for_rule(task: str, rule_name: str) -> str:
    if task == "gender":
        if rule_name.startswith("female_"):
            return "female"
        if rule_name.startswith("male_"):
            return "male"
    if task == "occupation":
        if rule_name.startswith("politics_"):
            return "politics"
        if rule_name.startswith("creator_"):
            return "creator"
        if rule_name.startswith("sports_"):
            return "sports"
    raise ValueError(f"Unknown rule target for {task}: {rule_name}")


def rules_for_task(task: str) -> List[Dict[str, str]]:
    if task == "gender":
        return [
            {
                "name": "female_flag_from_male_high_relationship_minus_male_2p0",
                "change": "male -> female",
                "conditions": "pred == male AND relationship_minus_male_role >= 2.0",
                "description": "Exploratory: if Fusion predicts male but relationship-minus-male-role is high, simulate correction to female.",
            },
            {
                "name": "female_flag_from_male_high_female_context_7p0",
                "change": "male -> female",
                "conditions": "pred == male AND female_context_minus_male_role >= 7.0",
                "description": "Exploratory: if Fusion predicts male but female-context-minus-male-role is high, simulate correction to female.",
            },
            {
                "name": "male_flag_from_female_low_relationship_minus_male_0p8",
                "change": "female -> male",
                "conditions": "pred == female AND relationship_minus_male_role <= 0.8",
                "description": "Exploratory: if Fusion predicts female but relationship-minus-male-role is low, simulate correction to male.",
            },
        ]

    if task == "occupation":
        return [
            {
                "name": "politics_recover_from_creator_high_politics_minus_creator_4p5",
                "change": "creator -> politics",
                "conditions": "pred == creator AND politics_minus_creator >= 4.5",
                "description": "If Fusion predicts creator but politics-vs-creator ratio is very high, simulate correction to politics.",
            },
            {
                "name": "politics_recover_from_creator_high_politics_minus_creator_6p0",
                "change": "creator -> politics",
                "conditions": "pred == creator AND politics_minus_creator >= 6.0",
                "description": "Stricter version of politics recovery from creator.",
            },
            {
                "name": "creator_recover_from_performer_low_performer_advantage",
                "change": "performer -> creator",
                "conditions": "pred == performer AND performer_minus_creator <= 0.6 AND fan_minus_creator <= 0.0",
                "description": "If Fusion predicts performer but performer/fan advantage over creator is weak, simulate correction to creator.",
            },
            {
                "name": "sports_recover_from_performer_high_sports_minus_performer_2p0",
                "change": "performer -> sports",
                "conditions": "pred == performer AND sports_minus_performer >= 2.0",
                "description": "If Fusion predicts performer but sports advantage is high, simulate correction to sports.",
            },
        ]
    raise ValueError(task)


def simulate_rule(rows: List[Dict[str, Any]], task: str, rule: Dict[str, str]) -> Dict[str, Any]:
    before_rows = base_rows(rows)
    after_rows = base_rows(rows)
    changed_examples = []
    target = new_label_for_rule(task, rule["name"])

    changed = improved = harmed = still_wrong = 0
    local_before_true = []
    local_before_pred = []
    local_after_pred = []

    for row, out_row in zip(rows, after_rows):
        if not rule_applies(row, task, rule["name"]):
            continue

        old = pred_label(row)
        gold = true_label(row)
        if old == target:
            continue

        changed += 1
        before_correct = old == gold
        after_correct = target == gold
        if after_correct and not before_correct:
            improved += 1
        elif before_correct and not after_correct:
            harmed += 1
        elif not after_correct:
            still_wrong += 1

        out_row["_sim_pred"] = target
        local_before_true.append(gold)
        local_before_pred.append(old)
        local_after_pred.append(target)

        ex = deepcopy(row)
        ex["old_pred"] = old
        ex["new_pred"] = target
        ex["improved"] = after_correct and not before_correct
        ex["harmed"] = before_correct and not after_correct
        changed_examples.append(ex)

    global_before = metrics(before_rows)
    global_after = metrics(after_rows)

    local_before_acc = (
        sum(1 for t, p in zip(local_before_true, local_before_pred) if t == p) / changed
        if changed else 0.0
    )
    local_after_acc = (
        sum(1 for t, p in zip(local_before_true, local_after_pred) if t == p) / changed
        if changed else 0.0
    )

    return {
        "rule": rule,
        "changed": changed,
        "improved": improved,
        "harmed": harmed,
        "still_wrong": still_wrong,
        "global_before": global_before,
        "global_after": global_after,
        "global_delta_accuracy": global_after["accuracy"] - global_before["accuracy"],
        "global_delta_macro_f1": global_after["macro_f1"] - global_before["macro_f1"],
        "local_before_accuracy": local_before_acc,
        "local_after_accuracy": local_after_acc,
        "changed_examples": changed_examples,
    }


def format_ratio_snippet(row: Dict[str, Any], task: str) -> str:
    rf = row.get("ratio_features", {})
    if task == "gender":
        keys = [
            "female_minus_male_role",
            "relationship_minus_male_role",
            "family_minus_male_role",
            "female_context_minus_male_role",
        ]
    else:
        keys = [
            "performer_minus_creator",
            "creator_minus_performer",
            "fan_minus_creator",
            "performer_fan_minus_creator",
            "politics_minus_creator",
            "sports_minus_performer",
        ]
    return ", ".join(f"{k}={rf.get(k, 0.0):.2f}" for k in keys if k in rf)


def write_markdown(task: str, source_path: str, row_source: str, rows: List[Dict[str, Any]], results: List[Dict[str, Any]], out_path: str) -> None:
    baseline = metrics(base_rows(rows))
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(f"# Semantic Correction Rule Simulation: {task}\n\n")
        f.write("> This is an error-analysis simulation on existing predictions. It should not be reported as a final tuned test result.\n\n")
        f.write(f"Script version: `{SCRIPT_VERSION}`\n\n")
        f.write(f"Source semantic report: `{source_path}`\n\n")
        f.write(f"Profile row source: `{row_source}`\n\n")
        if row_source.endswith("partial"):
            f.write("> WARNING: The report did not contain full profile rows. Metrics below are partial and not global. Regenerate semantic signal reports with full `profiles`.\n\n")

        f.write("## Global baseline on all loaded profiles\n\n")
        f.write("| n | accuracy | macro_f1 |\n")
        f.write("| ---: | ---: | ---: |\n")
        f.write(f"| {baseline['n']} | {baseline['accuracy']:.4f} | {baseline['macro_f1']:.4f} |\n\n")

        f.write("## Rule results\n\n")
        f.write("| rule | change | conditions | changed | improved | harmed | still wrong | global Δacc | global Δmacro-F1 | global after acc | global after macro-F1 | local before acc | local after acc |\n")
        f.write("| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n")
        for res in results:
            rule = res["rule"]
            f.write(
                f"| `{rule['name']}` | {rule['change']} | `{rule['conditions']}` "
                f"| {res['changed']} | {res['improved']} | {res['harmed']} | {res['still_wrong']} "
                f"| {res['global_delta_accuracy']:+.4f} | {res['global_delta_macro_f1']:+.4f} "
                f"| {res['global_after']['accuracy']:.4f} | {res['global_after']['macro_f1']:.4f} "
                f"| {res['local_before_accuracy']:.4f} | {res['local_after_accuracy']:.4f} |\n"
            )

        f.write("\n## Changed examples by rule\n\n")
        for res in results:
            rule = res["rule"]
            f.write(f"### `{rule['name']}`\n\n")
            f.write(f"{rule['description']}\n\n")
            examples = res["changed_examples"]
            if not examples:
                f.write("No changed profiles.\n\n")
                continue
            f.write("| id | true | old pred | new pred | improved | harmed | tokens | key ratios | top keyword hits |\n")
            f.write("| --- | --- | --- | --- | ---: | ---: | ---: | --- | --- |\n")
            for ex in examples[:30]:
                f.write(
                    f"| {profile_id(ex)} | {true_label(ex)} | {ex.get('old_pred', '')} | {ex.get('new_pred', '')} "
                    f"| {ex.get('improved')} | {ex.get('harmed')} | {token_count(ex)} "
                    f"| {format_ratio_snippet(ex, task)} | {top_hits(ex)} |\n"
                )
            f.write("\n")

        f.write("## Interpretation note\n\n")
        if task == "gender":
            f.write("For gender, rules are mainly explanatory. Relationship and female-context ratios can flag uncertain cases, but they should not be treated as reliable correction rules without a separate validation setup.\n")
        else:
            f.write("For occupation, rules should be interpreted as diagnostic probes. A positive delta suggests that the semantic feature direction matches some real errors, but the rule may still overfit the analyzed test split.\n")


def analyze_task(task: str) -> Dict[str, Any]:
    source_path = os.path.join(INPUT_DIR, TASK_FILES[task])
    report = read_json(source_path)
    rows_raw, row_source = load_profile_rows(report)
    rows = [add_ratio_features(r, task) for r in rows_raw if true_label(r) and pred_label(r)]

    print(f"[INFO] {task}: loaded profile rows = {len(rows)} from {row_source}")
    if len(rows) != 400:
        print(
            f"[WARN] {task}: expected 400 rows for PAN test, got {len(rows)}. "
            "If this is not intended, regenerate semantic signal reports with full profile rows."
        )

    results = [simulate_rule(rows, task, rule) for rule in rules_for_task(task)]

    ensure_dir(OUTPUT_DIR)
    md_path = os.path.join(OUTPUT_DIR, f"{task}_semantic_rule_simulation.md")
    json_path = os.path.join(OUTPUT_DIR, f"{task}_semantic_rule_simulation.json")

    write_markdown(task, source_path, row_source, rows, results, md_path)

    serializable = {
        "script_version": SCRIPT_VERSION,
        "task": task,
        "source_path": source_path,
        "row_source": row_source,
        "n_rows": len(rows),
        "global_baseline": metrics(base_rows(rows)),
        "results": results,
    }
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(serializable, f, ensure_ascii=False, indent=2)

    print(f"[OK] Saved {md_path}")
    print(f"[OK] Saved {json_path}")
    return serializable


def write_summary(all_results: Dict[str, Dict[str, Any]]) -> None:
    path = os.path.join(OUTPUT_DIR, "semantic_rule_simulation_summary.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Semantic Rule Simulation Summary\n\n")
        f.write(f"Script version: `{SCRIPT_VERSION}`\n\n")
        f.write("> Diagnostic post-hoc simulation on existing HybridV4 predictions. Do not report this as a final tuned test result.\n\n")
        for task, data in all_results.items():
            base = data["global_baseline"]
            f.write(f"## {task}\n\n")
            f.write(f"Rows loaded: **{data['n_rows']}** from `{data['row_source']}`\n\n")
            f.write(f"Global baseline accuracy: **{base['accuracy']:.4f}**, macro-F1: **{base['macro_f1']:.4f}**.\n\n")
            f.write("| rule | changed | improved | harmed | global Δaccuracy | global Δmacro-F1 | local before acc | local after acc |\n")
            f.write("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n")
            for res in data["results"]:
                f.write(
                    f"| `{res['rule']['name']}` | {res['changed']} | {res['improved']} | {res['harmed']} "
                    f"| {res['global_delta_accuracy']:+.4f} | {res['global_delta_macro_f1']:+.4f} "
                    f"| {res['local_before_accuracy']:.4f} | {res['local_after_accuracy']:.4f} |\n"
                )
            f.write("\n")
    print(f"[OK] Saved {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Simulate semantic correction rules for HybridV4 error analysis.")
    parser.add_argument("--task", choices=["gender", "occupation", "all"], default="all")
    args = parser.parse_args()

    tasks = ["gender", "occupation"] if args.task == "all" else [args.task]
    all_results = {task: analyze_task(task) for task in tasks}
    if len(all_results) > 1:
        write_summary(all_results)


if __name__ == "__main__":
    main()
