TARGET_LABEL = "occupation"

BATCH_SIZE = 32
LEARNING_RATE = 1e-3
NUM_EPOCHS = 5
WEIGHT_DECAY = 0.01

RANDOM_SEED = 42
VAL_RATIO = 0.1

CLASSIFIER_TYPE = "mlp"   # "linear" oder "mlp"
HIDDEN_DIM = 128
DROPOUT = 0.4

POOLING_STRATEGY = "mean"
NORMALIZE_INPUTS = True

SAVE_CHECKPOINTS = True
SAVE_PREDICTIONS = True

EARLY_STOPPING_PATIENCE = 2
EARLY_STOPPING_MIN_DELTA = 1e-4