MODEL_NAME = "google-bert/bert-base-uncased"
MAX_LENGTH = 512

MAX_FOLLOWERS = 3
MAX_TWEETS_PER_FOLLOWER = 20
MAX_CHARS = 10000

INCLUDE_SUPP = False

OUTPUT_DIRNAME = "bert_tokenized"

URL_TOKEN = "[URL]"
MENTION_TOKEN = "[MENTION]"

BATCH_SIZE = 32
SAVE_PRETTY_JSON = False